#Use Official PHP with Apache
FROM php:8.1-apache

#Install required php extensions for laravel
RUN apt-get update && apt-get install -y \ git unzip libpq-dev zip \ && docker-php-ext-install pdo pdo_mysql pdo_psql zip 

#Enable apache mod_rewrite (needed for laravel routing)
RUN a2enmod rewrite

#set apache document root ot /var/www/html/public
RUN sed -i 's|/var/www/html|/var/www/public|g' /etc/apache2/sites-available/000-default.conf\
&& sed -i 's|var/www/html|public|g' /etc/apache2/apache2.conf

#copy app code
COPY . /var/www/html/

#create uploads folder and set permissions
RUN mkdir -p /var/www/html/public/uploads\ && chown -R www-data:www-data /var/www/html/public/uploads \
 && chmod -R 775 /var/www/html/public/uploads
 
 #set working directory
 WORKDIR /var/www/html

 #Install composer //changes
 COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

 #install laravel dependencies
 RUN composer install --no-dev --optimize-autoloader

 #set permissions for laravel storage and cache
 RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache 

 #expose render require poet
 EXPOSE 10000

 #start apache 
 CMD ["apache2-foreground"]
